# 项目相关配置
ruoyi:
  # 名称
  name: frog
  # 版本
  version: 1.3.3
  # 版权年份
  copyrightYear: 2028
  # 实例演示开关
  demoEnabled: true

  # 文件路径，以uploadPath结尾 示例（ Windows配置 D:/uploadPath，Linux配置 /uploadPath, Mac /Users/xxx）
  profile: C:\Users\tanmin\Desktop\智农物链\znwl-agriculture-server\uploadPath
  #  profile: F:/ny/frog-smart-agriculture-master/frog-agriculture-server/uploadPath

  #  profile: C:/Users/tanmin/Desktop/区块链技术应用/若依农业/frog-smart-agriculture-master/frog-agriculture-server/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.frog.iot: warn
    com.frog.agriculture: info
    org.springframework: warn
    com.frog.sip: info
# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    #    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/znwl_agriculture?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5                                       # 初始化大小
    min-idle: 10                                          # 最小连接数
    max-active: 50                                        # 最大连接数
    max-wait: 100000                                       # 获取连接时的最大等待时间
    min-evictable-idle-time-millis: 300000                # 一个连接在池中最小生存的时间，单位是毫秒
    time-between-eviction-runs-millis: 60000              # 多久才进行一次检测需要关闭的空闲连接，单位
    test-while-idle: true
    ##阿里连接池
    druid:
      # 主库数据源
      master:
        #        url: jdbc:mysql://localhost:3306/frog_agriculture?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        url: jdbc:mysql://localhost:3306/znwl_agriculture?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:

      # TDengine数据库
      tdengine-server:
        # 默认不启用TDengine，true=启用，false=不启用
        enabled: false
        driverClassName: com.taosdata.jdbc.TSDBDriver
        url: jdbc:TAOS://localhost:6030/znwl_agriculture?timezone=Asia/Beijing&charset=utf-8
        username: root
        password: taosdata
        dbName: frog

      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: frog
        login-password: wumei-smart
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    #    password: frog
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # mqtt 配置
        # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)
  task:
    execution:
      pool:
        core-size: 10         # 最小连接数
        max-size: 30          # 最大连接数
        queue-capacity: 3000  # 最大容量

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklfrogrstuvwxyz
  # 令牌有效期（默认30分钟）1440为一天
  expireTime: 1440

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.frog.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

##########################################################
#mybatis-plus:
#  # 指定 Mapper XML 文件的位置，使用 classpath 通配符指定路径
#  #  mapper-locations: classpath:/mapper/*.xml
#  # 指定实体类的包路径，用于自动扫描并注册类型别名
#  typeAliasesPackage: com.frog.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: com.frog.IaAgriculture.entity
#  global-config:
#    db-config:
#      id-type: input
#      # 驼峰下划线转换（将数据库字段的下划线命名规则转换为 Java 实体类属性的驼峰命名规则）
#      db-column-underline: true
#      # 刷新 mapper
#      refresh-mapper: true
#  configuration:
#    # 将 Java 实体类属性的驼峰命名规则转换为数据库字段的下划线命名规则
#    map-underscore-to-camel-case: true
#    # 查询结果中包含空值的列，在映射的时候，不会映射这个字段
#    call-setters-on-nulls: true
#    # 开启 sql.txt 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 关闭 sql.txt 日志
#    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
mybatis-plus:
  # 扫描所有 Mapper XML 文件
  mapper-locations: classpath*:mapper/**/*.xml

  # 自动扫描多个包路径的实体类，并注册为类型别名
  type-aliases-package: com.frog.**.domain

  # 加载全局的 MyBatis 配置文件（可选）
  config-location: classpath:mybatis/mybatis-config.xml





#  global-config:
#    db-config:
#      # 手动设置主键（input 表示主键在插入时由代码指定）
#      id-type: input
#      # 数据库字段和 Java 属性之间的驼峰与下划线自动映射
#      db-column-underline: true
#      # SQL 文件变更时自动刷新 Mapper（开发阶段可启用）
#      refresh-mapper: true

#  configuration:
#    # Java 实体类的驼峰命名和数据库字段的下划线命名之间的自动转换
#    map-underscore-to-camel-case: true
#    # 查询结果中如果列值为空，不会映射该字段
#    call-setters-on-nulls: true
#    # 启用控制台 SQL 日志输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

system:
  peers:  10.0.12.40:20200
  groupId: 1
  node: 1
  certPath: conf
  privateKey: "213777107e3e6444e03ef10add84e95be071e5bca769dcad77afec6765fb5be7"
  contract:
    insurePlatformAddress: "0xc99a42a65608dc0e6e726ffc490489e67372fabd"


#mqtt配置
mqtt:
  broker: "tcp://127.0.0.1:1883"
  clientId: "java@122222"
  userName: "znwl@java1"
  password: "znwl@java1"
  subTopic: "pop"
# 条形码前端地址
barcode:
  path: http://127.0.0.1:8080/#/mobile?id=
